// Code generated by Clue Mock Generator v1.2.4, DO NOT EDIT.
//
// Command:
// $ cmg gen douglasthrift.net/presence/ifttt

package mockifttt

import (
	"context"

	"github.com/stretchr/testify/assert"
	"goa.design/clue/mock"

	"douglasthrift.net/presence/ifttt"
)

type (
	Client struct {
		m      *mock.Mock
		assert *assert.Assertions
	}

	ClientTriggerFunc func(ctx context.Context, present bool) (event string, values *ifttt.Values, err error)
)

func NewClient(t assert.TestingT) *Client {
	var (
		m              = &Client{mock.New(), assert.New(t)}
		_ ifttt.Client = m
	)
	return m
}

func (m *Client) AddTrigger(f ClientTriggerFunc) {
	m.m.Add("Trigger", f)
}

func (m *Client) SetTrigger(f ClientTriggerFunc) {
	m.m.Set("Trigger", f)
}

func (m *Client) Trigger(ctx context.Context, present bool) (event string, values *ifttt.Values, err error) {
	if f := m.m.Next("Trigger"); f != nil {
		return f.(ClientTriggerFunc)(ctx, present)
	}
	m.assert.Fail("unexpected Trigger call")
	return "", nil, nil
}

func (m *Client) HasMore() bool {
	return m.m.HasMore()
}
