version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: saturday
      time: "12:00"
      timezone: America/Los_Angeles
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: saturday
      time: "12:00"
      timezone: America/Los_Angeles
