version: 2
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - freebsd
      - linux
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
      - riscv64
    targets: # work around skipping FreeBSD RISC-V target
      - freebsd_386_sse2
      - freebsd_amd64_v1
      - freebsd_arm_6
      - freebsd_arm64_v8.0
      - freebsd_riscv64_rva20u64
      - linux_386_sse2
      - linux_amd64_v1
      - linux_arm_6
      - linux_arm64_v8.0
      - linux_riscv64_rva20u64
    main: ./cmd/presence
archives:
  - formats: [tar.xz]
    wrap_in_directory: true
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.sha256"
release:
  prerelease: auto
