before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - freebsd
      - linux
    main: ./cmd/presence
archives:
  - format: tar.xz
    wrap_in_directory: true
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.sha256"
release:
  prerelease: auto
